# Generated by Django 4.0.6 on 2022-08-01 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                ("date_uploaded", models.DateField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="restaurants.restaurant"),
                ),
            ],
        ),
    ]
