# Generated by Django 4.0.6 on 2022-08-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="description",
            field=models.TextField(default="A system admininistrator"),
            preserve_default=False,
        ),
    ]
