# Generated by Django 4.0.6 on 2022-08-01 14:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_menu"),
        ("employees", "0002_employee_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_voted", models.DateField(auto_now_add=True)),
                (
                    "points",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(3),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="employees.employee")),
                ("menu", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="restaurants.menu")),
            ],
        ),
    ]
